# Generated by Django 5.2 on 2025-04-07 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/avatar'),
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('answer', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('question', 'user')},
        ),
        migrations.AddConstraint(
            model_name='answerlike',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', -1), ('value__lte', 1)), name='answer_value_check'),
        ),
        migrations.AddConstraint(
            model_name='questionlike',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', -1), ('value__lte', 1)), name='question_value_check'),
        ),
    ]
