# Generated by Django 5.2 on 2025-04-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_answerlike_user_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='value',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='value',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
