# Generated by Django 5.2 on 2025-05-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_answerlike_value_alter_questionlike_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
