# Generated by Django 5.2 on 2025-05-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at']},
        ),
    ]
