# Generated by Django 5.2 on 2025-05-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_answer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-is_correct', '-created_at']},
        ),
    ]
