# Generated by Django 5.2 on 2025-05-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_answer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/fox.jpg', null=True, upload_to='avatars/'),
        ),
    ]
