# Generated by Django 5.2 on 2025-05-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_answerlike_answer_value_check_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at']},
        ),
    ]
